### ISSUE TITLE
Version 2.2 Release

### ISSUE THREAD

**Issue by ryanhammonds** [neurodsp-tools/neurodsp#261]
I've aggregate/organized the changes since the last release to help with the 2.2 changelog and to track what's left to be done before the next release.

@TomDonoghue feel free to change this as you see fit. I think wrapping up open PRs marks a good target to release 2.2, but feel free to add additional to-dos here.

#### Aperiodic
- [x] Detrended Fluctuation Analysis (#167)
- [x] IRASA (#212)
- [x] Autocorrelation (#217)

#### Simulation
- [x] Burst detection bug fix (#220)
- [x] Timeseries with defined spectral parameters (i.e. height, width, center) (#221)
- [x] Timeseries with defined Lorentzian parameters (i.e. chi1, chi2, knee) (#222)
- [x] Define bursts based on set durations (#239)
- [x] Extrema phase shifting (i.e. trough-to-trough or peak-to-peak) (#247)
- [x] Custom cycle support (#248)
- [x] Cycle length fix (#250)
- [x] Variable oscillations parameters (i.e. vary cycle simulation parameters on a cycle-by-cycle basis) (#252)
- [x] One-sided asymmetry (#254)
- [x] Simulate fractional Gaussian noise and fractional Brownian motion (#216)
- [x] Asymmetrical gaussian cycles (#228)
- [x] Simulate spikes of action potentials (#259)

#### Plotting
- [x] 2d array plotting (timeseries: #246, spectra: #269)
- [x] Labeling fix (#255)
- [x] Improved tests (#255)
- [x] Plotting saving updates  (#258, #260)
- [x] Plot bug fixes (#255)

#### Maintenance
- [x] Deprecate increase_n argument of `robust_hilbert` (#215)
- [x] Error for invalid transition bands (#267)
- [x] Improved speed of multidim decorator (#264)

#### Documentation
- [x] Tutorial for Morlet wavelets (#226)
- [x] Tutorials for DFA, IRASA, and Autocorrelation (#231)
- [x] Tutorials and updates for lagged coherence and sliding window matching (#230)

**Comment by TomDonoghue** [comment]
This looks great, thanks for doing this @ryanhammonds! 

I don't we want to add anything beyond the current open PRs for 2.2, as soon as we get the open things merged we can do a new release.

**Comment by ryanhammonds** [comment]
Hi @TomDonoghue, I caught up today on all the open PRs and they should be ready to go. I'll wait to merge the open PRs until you get a chance to approve them too. We've both already reviewed them so hopefully it won't be too much work. After that, I'll start preparing a new release!

**Comment by ryanhammonds** [comment]
Hi @TomDonoghue, what do you think about removing #235 from 2.2 and getting a release out soon? I was going to release a new bycycle version but noticed it requires neurodsp 2.2 and it seems better to release with a neurodsp pypi dependency rather thank a link to the main branch.

**Comment by TomDonoghue** [comment]
@ryanhammonds - yes, I think that is a good idea! We should just get a new release out at this point, and there's no reason not to move #235 into a 2.3 release! Sorry for dropping off on working on the remaining PRs to get the release out!

The last open questions then seems to be whether there are things in #275, #277, and #303 that should be prioritized into 2.2. I _think_ #277 can merge in quick, but the other two seem to have some open questions - can you do an a quick status check and see what you think should happen with them? If you tag me in, I'll do my best to help with anything over the next few days.

**Comment by ryanhammonds** [comment]
Yeah, I think #277 can be merged as is. #275 and #303 are smaller bugs / edge cases that can wait until 2.3 or maybe a smaller minor update (2.2.1).

So I can merge #277 (lmk if you want to check over it first) and then go ahead and release if that sounds good to you?

**Comment by TomDonoghue** [comment]
This sounds like a good plan to me! I agree that #275 and #303 are minor enough points to be merged into a future release. 

I had a quick check of #277, and that looks good to merge!

There is also #299 open, which most notably adds the 'aperiodic' module to the list of sub-modules. When you are ready to release, can you have a quick check for anything else worth adding into the readme, and then merge that?

Also, also - it crossed my mind that testing against 3.10 should now be supported from Github actions, so I have added that in #307. As long as that looks good to you, do you want to merge that in as well, and then 2.2 officially supports 3.10?

Otherwise I think we are ready for a new release - are you good to go with that after merging these last things in? Other than using this issue to list the updates on release page, I think it should be a normal release! Let me know if you need anything else from me - but there's nothing else I want to check in on, so also feel free to just go for it!
